FROM {{base_image}}
RUN \
    micromamba install -y -n base {{channel_opts}} {{target}} \
    && micromamba install -y -n base conda-forge::procps-ng \
    {{base_packages}}
    && micromamba clean -a -y
USER root
