FROM {{base_image}}
RUN \
    micromamba install -y -n base {{channel_opts}} {{target}} \
    {{base_packages}}
    && micromamba env export --explicit > environment.lock.yml \
    && micromamba clean -a -y
USER root
ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"
